server:
  port: 8080

spring:

  datasource:
    # Base stock
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: 'postgres'
    password: 'postgres'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: 'true'